[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MorphQ"
version = "0.1.0"
description = "Metamorphic Testing for Qiskit Quantum Computing Platform"
dependencies = [
    "astpretty",
    "asttokens",
    "astunparse",
    "click",
    "coverage",
    "Deprecated",
    "docopt",
    "matplotlib",
    "networkx",
    "numpy",
    "pandas",
    "platformdirs",
    "psutil",
    "pydantic",
    "pytest",
    "PyYAML",
    "qiskit==1.2.4",
    "qiskit-aer==0.15.1",
    "qiskit-ibm-runtime==0.29.0",
    "rustworkx",
    "scipy",
    "seaborn",
    "termcolor",
    "tqdm",
]
